name: habla
description: Modern Spanish learning app (A1–B2) with free and paid paths, video news and GitHub Pages deployment.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

  # Flutter Material Icons
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/content/lessons.json
    - assets/content/news.json